# Lock gems that are part of the distribution
distribution_gemfile = File.expand_path("../../../../../../../../Gemfile", __FILE__)
instance_eval(IO.read(distribution_gemfile), distribution_gemfile)
source "https://rubygems.org"

gemspec

group :development do
  gem "sigar", :platform => "ruby"

  gem "chefstyle", "= 0.3.1"
  # gem 'pry-byebug'
  # gem 'pry-stack_explorer'
end
