        # Meant to be included in component Gemfiles at the beginning with:
        #
        #     instance_eval(IO.read("/opt/chefdk/Gemfile"), "/opt/chefdk/Gemfile")
        #
        # Override any existing gems with our own.
        require_relative "embedded/lib/ruby/gems/2.1.0/gems/chef-dk-0.14.25/tasks/gemfile_util"
        extend GemfileUtil
        gem "CFPropertyList", "2.3.2", override: true
gem "activesupport", "4.2.6", override: true
gem "addressable", "2.4.0", override: true
gem "app_conf", "0.4.2", override: true
gem "appbundler", "0.9.0", override: true
gem "artifactory", "2.3.2", override: true
gem "ast", "2.2.0", override: true
gem "autoparse", "0.3.3", override: true
gem "aws-sdk", "2.3.4", override: true
gem "aws-sdk-core", "2.3.4", override: true
gem "aws-sdk-resources", "2.3.4", override: true
gem "aws-sdk-v1", "1.66.0", override: true
gem "berkshelf", "4.3.3", override: true
gem "berkshelf-api-client", "2.0.2", override: true
gem "binding_of_caller", "0.7.2", override: true
gem "buff-config", "1.0.1", override: true
gem "buff-extensions", "1.0.0", override: true
gem "buff-ignore", "1.1.1", override: true
gem "buff-ruby_engine", "0.1.0", override: true
gem "buff-shell_out", "0.2.0", override: true
gem "builder", "3.2.2", override: true
gem "bundler", "1.12.4", override: true
gem "byebug", "9.0.3", override: true
gem "celluloid", "0.16.0", override: true
gem "celluloid-io", "0.16.2", override: true
gem "chef", "12.10.24", override: true
gem "chef-config", "12.10.24", override: true
gem "chef-dk", "0.14.25", override: true
gem "chef-provisioning", "1.7.0", override: true
gem "chef-provisioning-aws", "1.9.0", override: true
gem "chef-provisioning-azure", "0.5.0", override: true
gem "chef-provisioning-fog", "0.18.0", override: true
gem "chef-provisioning-vagrant", "0.11.0", override: true
gem "chef-sugar", "3.3.0", override: true
gem "chef-vault", "2.9.0", override: true
gem "chef-zero", "4.6.2", override: true
gem "cheffish", "2.0.4", override: true
gem "chefspec", "4.7.0", override: true
gem "cleanroom", "1.0.0", override: true
gem "coderay", "1.1.1", override: true
gem "compat_resource", "12.9.1", override: true
gem "cookbook-omnifetch", "0.2.2", override: true
gem "cucumber-core", "1.4.0", override: true
gem "debug_inspector", "0.0.2", override: true
gem "dep-selector-libgecode", "1.2.0", override: true
gem "dep_selector", "1.0.3", override: true
gem "diff-lcs", "1.2.5", override: true
gem "diffy", "3.1.0", override: true
gem "docker-api", "1.26.2", override: true
gem "erubis", "2.7.0", override: true
gem "excon", "0.49.0", override: true
gem "extlib", "0.9.16", override: true
gem "faraday", "0.9.2", override: true
gem "fauxhai", "3.4.0", override: true
gem "ffi", "1.9.10", override: true
gem "ffi-rzmq", "2.0.4", override: true
gem "ffi-rzmq-core", "1.0.5", override: true
gem "ffi-yajl", "2.2.3", override: true
gem "fission", "0.5.0", override: true
gem "fog", "1.38.0", override: true
gem "fog-aliyun", "0.1.0", override: true
gem "fog-atmos", "0.1.0", override: true
gem "fog-aws", "0.9.2", override: true
gem "fog-brightbox", "0.10.1", override: true
gem "fog-cloudatcost", "0.1.2", override: true
gem "fog-core", "1.39.0", override: true
gem "fog-dynect", "0.0.3", override: true
gem "fog-ecloud", "0.3.0", override: true
gem "fog-google", "0.1.0", override: true
gem "fog-json", "1.0.2", override: true
gem "fog-local", "0.3.0", override: true
gem "fog-openstack", "0.1.5", override: true
gem "fog-powerdns", "0.1.1", override: true
gem "fog-profitbricks", "0.0.5", override: true
gem "fog-rackspace", "0.1.1", override: true
gem "fog-radosgw", "0.0.5", override: true
gem "fog-riakcs", "0.1.0", override: true
gem "fog-sakuracloud", "1.7.5", override: true
gem "fog-serverlove", "0.1.2", override: true
gem "fog-softlayer", "1.1.1", override: true
gem "fog-storm_on_demand", "0.1.1", override: true
gem "fog-terremark", "0.1.0", override: true
gem "fog-vmfusion", "0.1.0", override: true
gem "fog-voxel", "0.1.0", override: true
gem "fog-vsphere", "0.7.0", override: true
gem "fog-xenserver", "0.2.3", override: true
gem "fog-xml", "0.1.2", override: true
gem "foodcritic", "6.3.0", override: true
gem "formatador", "0.2.5", override: true
gem "fuzzyurl", "0.8.0", override: true
gem "gherkin", "3.2.0", override: true
gem "git", "1.3.0", override: true
gem "google-api-client", "0.8.6", override: true
gem "googleauth", "0.5.1", override: true
gem "gssapi", "1.2.0", override: true
gem "guard", "2.13.0", override: true
gem "gyoku", "1.3.1", override: true
gem "hashie", "3.4.4", override: true
gem "highline", "1.7.8", override: true
gem "hitimes", "1.2.4", override: true
gem "httpclient", "2.7.2", override: true
gem "i18n", "0.7.0", override: true
gem "inflecto", "0.0.2", override: true
gem "inifile", "3.0.0", override: true
gem "inspec", "0.22.0", override: true
gem "ipaddress", "0.8.3", override: true
gem "jmespath", "1.2.4", override: true
gem "json", "1.8.3", override: true
gem "json_pure", "1.8.3", override: true
gem "jwt", "1.5.1", override: true
gem "kitchen-ec2", "1.0.0", override: true
gem "kitchen-inspec", "0.13.0", override: true
gem "kitchen-vagrant", "0.20.0", override: true
gem "knife-push", "1.0.1", override: true
gem "knife-spork", "1.6.1", override: true
gem "knife-supermarket", "0.2.4", override: true
gem "knife-windows", "1.4.1", override: true
gem "launchy", "2.4.3", override: true
gem "libyajl2", "1.2.0", override: true
gem "listen", "3.0.7", override: true
gem "little-plugger", "1.1.4", override: true
gem "logging", "2.1.0", override: true
gem "lumberjack", "1.0.10", override: true
gem "macaddr", "1.7.1", override: true
gem "memoist", "0.14.0", override: true
gem "method_source", "0.8.2", override: true
gem "mime-types", "2.99.1", override: true
gem "mini_portile2", "2.0.0", override: true
gem "minitar", "0.5.4", override: true
gem "minitest", "5.9.0", override: true
gem "mixlib-authentication", "1.4.0", override: true
gem "mixlib-cli", "1.6.0", override: true
gem "mixlib-config", "2.2.1", override: true
gem "mixlib-install", "1.0.11", override: true
gem "mixlib-log", "1.6.0", override: true
gem "mixlib-shellout", "2.2.6", override: true
gem "mixlib-versioning", "1.1.0", override: true
gem "molinillo", "0.4.5", override: true
gem "multi_json", "1.12.0", override: true
gem "multipart-post", "2.0.0", override: true
gem "nenv", "0.3.0", override: true
gem "net-scp", "1.2.1", override: true
gem "net-sftp", "2.1.2", override: true
gem "net-ssh", "3.1.1", override: true
gem "net-ssh-gateway", "1.2.0", override: true
gem "net-ssh-multi", "1.2.1", override: true
gem "net-telnet", "0.1.1", override: true
gem "nio4r", "1.2.1", override: true
gem "nokogiri", "1.6.7.2", override: true
gem "nori", "2.6.0", override: true
gem "notiffany", "0.0.8", override: true
gem "octokit", "4.3.0", override: true
gem "ohai", "8.16.0", override: true
gem "opscode-pushy-client", "1.3.4", override: true
gem "os", "0.9.6", override: true
gem "paint", "1.0.1", override: true
gem "parser", "2.3.1.0", override: true
gem "plist", "3.2.0", override: true
gem "polyglot", "0.3.5", override: true
gem "proxifier", "1.0.3", override: true
gem "pry", "0.10.3", override: true
gem "pry-byebug", "3.4.0", override: true
gem "pry-remote", "0.1.8", override: true
gem "pry-stack_explorer", "0.4.9.2", override: true
gem "r-train", "0.12.0", override: true
gem "rack", "1.6.4", override: true
gem "rainbow", "2.1.0", override: true
gem "rake", "11.1.2", override: true
gem "rb-fsevent", "0.9.7", override: true
gem "rb-inotify", "0.9.7", override: true
gem "rb-readline", "0.5.3", override: true
gem "rbvmomi", "1.8.2", override: true
gem "rdoc", "4.2.2", override: true
gem "retriable", "1.4.1", override: true
gem "retryable", "2.0.3", override: true
gem "ridley", "4.5.1", override: true
gem "rspec", "3.4.0", override: true
gem "rspec-core", "3.4.4", override: true
gem "rspec-expectations", "3.4.0", override: true
gem "rspec-its", "1.2.0", override: true
gem "rspec-mocks", "3.4.1", override: true
gem "rspec-support", "3.4.1", override: true
gem "rspec_junit_formatter", "0.2.3", override: true
gem "ruby-prof", "0.15.9", override: true
gem "ruby-progressbar", "1.8.1", override: true
gem "ruby-shadow", "2.5.0", override: true
gem "rubyntlm", "0.6.0", override: true
gem "rubyzip", "1.2.0", override: true
gem "rufus-lru", "1.1.0", override: true
gem "safe_yaml", "1.0.4", override: true
gem "sawyer", "0.7.0", override: true
gem "semverse", "1.2.1", override: true
gem "serverspec", "2.35.0", override: true
gem "sfl", "2.2", override: true
gem "shellany", "0.0.1", override: true
gem "signet", "0.7.2", override: true
gem "slop", "3.6.0", override: true
gem "solve", "2.0.3", override: true
gem "specinfra", "2.57.2", override: true
gem "stuartpreston-azure-sdk-for-ruby", "0.7.1", override: true
gem "syslog-logger", "1.6.8", override: true
gem "systemu", "2.6.5", override: true
gem "test-kitchen", "1.8.0", override: true
gem "thor", "0.19.1", override: true
gem "thread_safe", "0.3.5", override: true
gem "timers", "4.0.4", override: true
gem "treetop", "1.6.5", override: true
gem "trollop", "2.1.2", override: true
gem "tzinfo", "1.2.2", override: true
gem "ubuntu_ami", "0.4.1", override: true
gem "uuid", "2.3.8", override: true
gem "uuidtools", "2.1.5", override: true
gem "varia_model", "0.4.1", override: true
gem "winrm", "1.8.1", override: true
gem "winrm-elevated", "0.4.0", override: true
gem "winrm-fs", "0.4.2", override: true
gem "wmi-lite", "1.0.0", override: true
gem "xml-simple", "1.1.5", override: true
gem "yajl-ruby", "1.2.1", override: true
gem "yard", "0.8.7.6", override: true

