# Lock gems that are part of the distribution
distribution_gemfile = File.expand_path("../../../../../../../../Gemfile", __FILE__)
instance_eval(IO.read(distribution_gemfile), distribution_gemfile)
source "https://rubygems.org"
gemspec

group :guard do
  gem "guard-rspec",    :require => nil
  gem "guard-rubocop",  :require => nil
end

group :test do
  gem "codeclimate-test-reporter", :require => nil
end
