# Lock gems that are part of the distribution
distribution_gemfile = File.expand_path("../../../../../../../../Gemfile", __FILE__)
instance_eval(IO.read(distribution_gemfile), distribution_gemfile)
source 'https://rubygems.org'

gem 'foodcritic', :path => '.'

group :test do
  gem 'aruba', '~> 0.5'
  gem 'cucumber', '>= 2'
  gem 'minitest', '~> 5.3'
  gem 'simplecov', '~> 0.8'
end

group :development do
  gem 'chef', '~> 12.1'
  gem 'ronn', '~> 0.7'
  gem 'rubocop', '~> 0.20', require: false
end
