# Lock gems that are part of the distribution
distribution_gemfile = File.expand_path("../../../../../../../../Gemfile", __FILE__)
instance_eval(IO.read(distribution_gemfile), distribution_gemfile)
source 'https://rubygems.org'

# Specify your gem's dependencies in cookstyle.gemspec
gemspec
